# Generated by Django 4.2.26 on 2025-11-27 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_downloadlog_subscription_remove_userdownload_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='allowed_product_types',
        ),
        migrations.AddField(
            model_name='subscription',
            name='allowed_product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.producttype'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
