# Generated by Django 4.2.26 on 2025-11-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_subscription_allowed_product_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='allowed_product_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.producttype'),
        ),
    ]
