# Generated by Django 4.2.26 on 2025-11-27 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_subscription_allowed_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('daily_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Plan required to download this product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subscriptionplan'),
        ),
    ]
